### PR TITLE
Improved scoring

### PR DESCRIPTION
**Pull request by matthiasnoback**
Hi everyone,

I picked up the work based on #97. I came up  with a calculation that to me makes a lot of sense. See `Result::getScore()` and the comments inside it.

By normalizing the scores you basically end up with coordinates in a square of 1 by 1. The scores are based on the distance of each class to the top-right corner (the "worst" classes). In the green area, the score will be between 1 and 0. In the blue area, the score will be below 0.

diagram

I also added a CLI option to generate JSON output, since I'm working on some tool to generate a nice diagram based on the output. Right now it looks something like this:
screen shot 2017-10-04 at 16 21 06

I'm not quite ready to open-source that tool (since it's quite crappy atm ;)). But it would help to know if you'd be okay merging my changes in. I do realize that there is at least one breaking API change (you have to provide arguments to `Result::getScore()` now). And the overall behavior has changed, meaning that values like "minimum score" have to be revised by users. However, I think it's for the better. A minimum score of 0 basically cuts of any class that is below the line in the diagram, so it's okay to ignore them. One thing we could do is add a sanity check and warn the user that the minimum score provided should be lower than 1.

I'd be happy to hear your thoughts and please let me know if anything is not up to your standard.

### CODE REVIEW

**Comment by matthiasnoback** [comment]
In case you're interested to follow developments of the visualization tool: https://github.com/matthiasnoback/churn-php-visualization

**Comment by bmitch** [comment]
@matthiasnoback This looks very nice! Thanks, I'll take some time to look at it as soon as I can.

**Comment by matthiasnoback** [comment]
@bmitch Cool, I noticed some things that your CI tools want fixed, which should be easy (except maybe for the long variable names which I think definitely add meaning and should be allowed ;)). Also, it's ironic that Code Climate has built-in support for the "churn chart", but not for PHP, right?

**Comment by bmitch** [comment]
@matthiasnoback No problem. I will probably make that long variable name allowed. Always exceptions to the rules :)

Yeah too bad code climate does not have that. Maybe they will change?

**Comment by bmitch** [comment]
Thanks once again @matthiasnoback this is awesome. I'm going to tinker with it over the weekend and probably do some refactoring to the entire codebase before I mark a release.

**Comment by matthiasnoback** [comment]
Great, thank you too!

**Pull request merged**
