### PR TITLE
Release only releases

### PR DESCRIPTION
**Pull request by szepeviktor**
Please consider tagging releases with a `v`+semver as there are other kind of tags.

### CODE REVIEW

**Comment by villfa** [comment]
What kind of other tags are you mentioning?

I would prefer not change the format of the tags.
Instead of `v*`, is there a way to define a pattern like `\d.\d.\d`?

**Comment by szepeviktor** [comment]
> I would prefer not change the format of the tags.

Okay

https://github.com/symfony/symfony/releases
https://github.com/laravel/framework/releases
https://github.com/codeigniter4/CodeIgniter4/tags?after=v4.0.0-rc.2

**Comment by szepeviktor** [comment]
>  Instead of `v*`, is there a way to define a pattern like `\d+\.\d+\.\d+`?

Yes.
https://docs.github.com/en/enterprise-server@2.22/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
`[0-9]+.[0-9]+.[0-9]+`

**Comment by villfa** [comment]
Then if you could update your PR with this pattern I would gladly merge it.

**Comment by szepeviktor** [comment]
Done.

👋 good bye dear `v` 😿

**Comment by villfa** [comment]
Thanks @szepeviktor

**Comment by szepeviktor** [comment]
You're welcome.

**Pull request merged**
