### PR TITLE
Fix composer scripts for windows

### PR DESCRIPTION
**Pull request by villfa**
On Windows the command `composer test` produces the following error:
```
'vendor' is not recognized as an internal or external command
```
Removing *vendor/bin/* from the commands fixes this problem.

I also noticed some namespaces were wrong in the unit tests files so I fixed them.

### CODE REVIEW

**Comment by villfa** [comment]
@bmitch I've open this PR as a first step to fix #71 .
FYI, some tests related to the `FileManager` class don't pass. I tried to take a look but I couldn't come up with an easy fix so I let this PR as is.
If it's ok for you I'll try to fix the broken tests in another PR when I'll have time.

**Comment by bmitch** [comment]
Thanks @villfa - all the tests passed as far as I can see. I don't see any failing for `FileManager` but if I am missing something please feel free to open an issue and/or pull request!

**Comment by villfa** [comment]
@bmitch I should have specified that the tests fail only on windows.
I'll keep you posted if I make them pass.

**Comment by bmitch** [comment]
Ah makes sense! Perfect thank you @villfa !

**Pull request merged**
