### PR TITLE
Add Docker section to README.md

### PR DESCRIPTION
**Pull request by tommy-muehle**
Let me know if anything's not clear. Then I'll be happy to adjust this.

### CODE REVIEW

**Comment by mglaman** [comment]
I'm having hard conflicts on `bmitch/churn-php 0.3.1 requires symfony/yaml ^3.3` in global and local projects (Drupal based.) Since there is no phar this was a great workaround.

**Comment by Exadra37** [comment]
Correct docker command is `docker run --rm -ti -v $PWD:/app dockerizedphp/churn run /path/to/code`.

The typo is in `$(PWD)` that must be `$PWD` or `$($PWD)`.

**Comment by bmitch** [comment]
@tommy-muehle this is very cool. If you can make the adjustment that @Exadra37 pointed out then I will go ahead and merge this. Thanks.

**Comment by tommy-muehle** [comment]
@Exadra37 
Thanks for the hint! I updated the command. Under macOS is also the preceding command with ```$(PWD)``` possible. So I didn't realize it.

**Comment by bmitch** [comment]
Thanks @tommy-muehle

**Pull request merged**
